mailServer:
  host: smtp.gmail.com
  port: 587
  email: shopmubaohiemlht@gmail.com
  password: fqvx vhal umkx ugdh
  protocol: smtp
  isSSL: false

frontend:
  base-endpoint: http://localhost:5173

backend:
  base-endpoint: http://localhost:8080